name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout winsparkle
        uses: actions/checkout@v4
        with:
          repository: vslavik/winsparkle
          ref: refs/tags/v0.8.3
          path: winsparkle

      - name: Modify
        working-directory: winsparkle
        run: |
          (Get-Content "WinSparkle.sln" -Raw) `
            -replace "# Visual Studio Version 17", "# Visual Studio Version 16" `
            -replace "17.0.31919.166", "16.0.30320.27" | `
            Set-Content "WinSparkle.sln"

      - name: Fetch deps
        working-directory: winsparkle
        run: |
          git submodule update --init --recursive

      - name: Restore dependency packages
        working-directory: winsparkle
        run: |
          nuget restore

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Build
        working-directory: winsparkle
        run: msbuild WinSparkle.sln
          /t:Clean,Build `
          /p:Platform=x64 `
          /p:Configuration=Release `
          /p:WholeProgramOptimization=true `
          /p:FunctionLevelLinking=true `
          /p:EnableEnhancedInstructionSet=AdvancedVectorExtensions2

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: winsparkle
          path: |
            winsparkle/x64/Release/*.dll
