name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout winsparkle
        uses: actions/checkout@v4
        with:
          repository: vslavik/winsparkle
          ref: refs/tags/v0.8.3
          path: winsparkle

      - name: Modify
        run: |
          Move-Item -Path "WinSparkle.sln" -Destination "winsparkle/WinSparkle.sln" -Force

      - name: Fetch deps
        working-directory: winsparkle
        run: |
          git submodule update --init --recursive

      - name: Restore dependency packages
        working-directory: winsparkle
        run: |
          nuget restore

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: "16.11"
          msbuild-architecture: x64

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Build
        working-directory: winsparkle
        run: msbuild WinSparkle.sln
          /t:Clean,Build `
          /p:Platform=x64 `
          /p:Configuration=Release `
          /p:WholeProgramOptimization=true `
          /p:FunctionLevelLinking=true `
          /p:EnableEnhancedInstructionSet=AdvancedVectorExtensions2

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: winsparkle
          path: |
            winsparkle/x64/Release/*.dll
